### ISSUE TITLE
Går inte att visa bokningarna i Android-webbläsare

### ISSUE THREAD

**Issue by mangelito** [Kastanjen/bokalokalen#2]
Testat med Samsungs inbyggda, Chrome och Firefox

**Comment by frelar** [comment]
Jag har tyvärr ingen fungerande Andriod-enhet att testa med. Vi får lista ut något sätt att felsöka.

**Comment by frelar** [comment]
Jag installerade Android studio och några körningar i emulatorn säger mig att det verkar vara css klassen "pull-right" på knappen som orsakar problemet.
Denna klass var en nödlösning av rang så vi bör lista ut ett annat sätt att få knapparna på "rätt" plats.
